### ISSUE TITLE
Using

### ISSUE THREAD

**Issue by jarrett-flierl** [timwhite/yamm-fork#1]
Hi Tim, trying to run this script but having issues getting it to work

**Comment by timwsuqld** [comment]
@jarrett-flierl Unfortunately I no longer use this script, and Google sheets has changed a lot since this code was last modified. I would not be surprised if it didn't work nowadays, and I'll probably archive the repository for historical purposes.

**Comment by jarrett-flierl** [comment]
ahhh, no worries! Thanks for getting back to me
